import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import useDebounce from "~/utils/hooks/useDebounce";

const Home: NextPage = () => {
  const [userText, setUserText] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const debouncedUserText = useDebounce(userText, 500);

  useEffect(() => {
    if (debouncedUserText) {
      setIsTyping(true);

      // eslint-disable-next-line @typescript-eslint/no-empty-function
      setTimeout(() => {}, 3 * 1000);
      console.log(debouncedUserText);
      setIsTyping(false);
    } else {
      setIsTyping(false);
    }
  }, [debouncedUserText]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="grid h-screen grid-cols-2 bg-cyan-800 p-16">
        <div className="h-full bg-cyan-800 pr-2">
          <textarea
            spellCheck="false"
            className="h-full w-full resize-none"
            onChange={(event) => setUserText(event.target.value)}
          ></textarea>
        </div>
        <div className="flex h-full flex-col gap-4 bg-cyan-800 pl-2">
          <iframe className="h-1/2 w-full bg-white"></iframe>
          <div className="h-1/2 w-full bg-white"></div>
        </div>
      </main>
    </>
  );
};

export default Home;
